### ISSUE TITLE
BUG: New constructor argument wiring not up to date with actual constructor signature

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#3615]
Probably a regression from #3510 
Tested with Flow 9.2-beta2
FLOW_CONTEXT=Testing/Behat

When developing in testing context i regularly create new factories or add new constructor injections to factories.

Im my case i wanted to add the `ImageFactory` which is also just another final class with constructor injection and of implicit type prototype like this factory

```php
final class MyThingFactory
{
    public function __construct(
        private OneFactory $oneFactory,
        private OtherFactory $otherFactory,
        private ImageFactory $imageFactory,
    ) {
    }
```

> Uncaught Exception in Flow Too few arguments to function MyThingFactory::__construct(), 2 passed in Testing/SubContextBehat/Cache/Code/Flow_Object_Classes/Vendor_Endpoints_Controller_SomeController.php on line 371 and exactly 3 expected
> thrown in file Packages/.../MyThingFactory.php

Which means the place where `MyThingFactory` was injected - a controller - via

```php
    #[Flow\Inject()]
    protected MyThingFactory $myThingFactory;
```

did not instantiate the class properly and missed out on the new `$imageFactory`.

**Comment by mhsdesign** [comment]
Workaround either flush the cache (sadly fully) or comment out the root injection

```php
#[Flow\Inject()]
protected MyThingFactory $myThingFactory;
```

and run flow, and then comment it back in.

So the root cause seems to be that the place instantiating the class seems stale, but flow overall understood the changes to the file in principle.

CC @kitsunet

**Comment by kitsunet** [comment]
Alright this is a tricky one.

You do something you yourself said we can possibly remove in the future of Flow ;) You rely on auto injection for non singleton classes. As you noted yourself. The trick here is that a prototype must have a new instance for this injection. What happens when that is done via auto injection is that the proxy class contains a new call for the class. That was fine as empty `new MyThingFactory()` call before and the proxy constructor would sort out the necessary arguments to inject. However without proxy constructor we must sort this beforehand, so now the calling side (in your example the Controller that wants `MyThingFactory` injected) needs to sort this out, which means now the proxies contain a full constructor call filling in the arguments ala

```
new MyThingFactory(
  Bootstrap::staticObjectManager->get('OneFactory'), //  or some other call, depending on argument type etc.
  Bootstrap::staticObjectManager->get('OtherFactory'),
)
```

If you change MyThingFactory, it's own proxy is flushed but not all callers to the constructor, because we have no back reference here.

My personal opinion is that this is bad style, you cannot expect magic where magic is not welcomed. `MyThingFactory` should be a singleton which would solve the problem as then we would only embed a call to objectManager->get('MyThingFactory') into the controller. You can even singleton it via Objects.yaml to keep that out of the code ;)

However I am willing to consider a fix, it's just ugly either way.

A) We allow the ObjectManager to deal with prototypes, which it currently doesn't, then the call could be the same as fir a singleton and the shape of the constructor wouldn't matter. The objectmanager would just deal with creating a new instance. This would take away from the fact that prototypes shouldn't be injected in the first place.... And I am not a huge fan. It would probably be one of the easier fixes though.

B) We just flush all object classes on change -> this is detrimental to dev timings and probably not nice either, but surely an easy fix.

C) We build a reverse reference list of where such constructors are called. Complexity rises, bugs are likely, otherwise cleanest solution?!

I don't really like either of these and would rather say do not inject prototypes because it's bad. But 🤷

**Comment by mhsdesign** [comment]
ahh i see 🤦 yes i hate the feature somehow but i also just want to write plain php where i can.
I could definitely turn `MyThingFactory` into a singleton if this is the advice. Its just extra work always adding the `#[Flow\Scope("singleton")]` to all the beautiful factories which deliberately use constructor injection to be just php not any special stuff.

**Comment by kitsunet** [comment]
As said, put the scope: singleton into an Objects.yaml and the code stays the same ;)
